<?php

/**
 * @file
 * Handles the creation/display of islandora:sp-pdf objects.
 */

/**
 * Implements hook_theme().
 */
function islandora_pdf_theme($existing, $type, $theme, $path) {
  return [
    'islandora_pdf' => [
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-pdf',
      'pattern' => 'islandora_pdf__',
      'variables' => ['islandora_object' => NULL],
    ],
    'islandora_pdf_print' => [
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-pdf-print',
      'pattern' => 'islandora_pdf_print__',
      'variables' => ['islandora_object' => NULL],
    ],
  ];
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_pdf_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_pdf');
  // PDF Content Model.
  $pdf_content_model = $connection->repository->constructObject('islandora:sp_pdf');
  $pdf_content_model->owner = 'fedoraAdmin';
  $pdf_content_model->label = 'Islandora PDF Content Model';
  $pdf_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $pdf_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pdf_ds_composite_model.xml", FALSE);
  $pdf_content_model->ingestDatastream($datastream);
  // PDF Collection.
  $pdf_collection = $connection->repository->constructObject('islandora:sp_pdf_collection');
  $pdf_collection->owner = 'fedoraAdmin';
  $pdf_collection->label = 'PDF Collection';
  $pdf_collection->models = 'islandora:collectionCModel';
  $pdf_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $pdf_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pdf_collection_policy.xml", FALSE);
  $pdf_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $pdf_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $pdf_collection->ingestDatastream($datastream);
  return [
    'islandora_pdf' => [
      'title' => 'Islandora PDF',
      'objects' => [
        $pdf_content_model,
        $pdf_collection,
      ],
    ],
  ];
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_pdf_islandora_sp_pdf_islandora_view_object($object, $page_number, $page_size) {
  // @FIXME
// theme() has been renamed to _theme() and should NEVER be called directly.
// Calling _theme() directly can alter the expected output and potentially
// introduce security issues (see https://www.drupal.org/node/2195739). You
// should use renderable arrays instead.
//
//
// @see https://www.drupal.org/node/2195739
// $output = theme('islandora_pdf', array('islandora_object' => $object));

  return ['' => $output];
}

/**
 * Implements hook_islandora_view_print_object().
 */
function islandora_pdf_islandora_view_print_object($object) {
  // @FIXME
// theme() has been renamed to _theme() and should NEVER be called directly.
// Calling _theme() directly can alter the expected output and potentially
// introduce security issues (see https://www.drupal.org/node/2195739). You
// should use renderable arrays instead.
//
//
// @see https://www.drupal.org/node/2195739
// $output = theme('islandora_pdf_print', array('islandora_object' => $object));

  return ['pdf' => $output];
}

/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_pdf_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_pdf');
  return [
    'PDF MODS form' => [
      'form_file' => "$module_path/xml/islandora_pdf_form_mods.xml",
    ],
  ];
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_pdf_xml_form_builder_form_associations() {
  return [
    'islandora_pdf_mods_form' => [
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'PDF MODS form',
      'dsid' => 'MODS',
      'title_field' => ['titleInfo', 'title'],
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ],
  ];
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_pdf_islandora_sp_pdf_islandora_ingest_steps() {
  return [
    'islandora_pdf_file_upload' => [
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'Drupal\islandora_pdf\Form\PdfUploadForm',
      'module' => 'islandora_pdf',
    ],
  ];
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function islandora_pdf_islandora_sp_pdf_islandora_derivative() {
  $derivatives = [];
  $derivatives[] = [
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'TN',
    'weight' => '0',
    'function' => [
      'islandora_pdf_add_tn_derivative',
    ],
    'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
  ];
  $derivatives[] = [
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'PREVIEW',
    'weight' => '1',
    'function' => [
      'islandora_pdf_add_preview_derivative',
    ],
    'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
  ];
  if (\Drupal::config('islandora_pdf.settings')->get('islandora_pdf_create_fulltext')) {
    $derivatives[] = [
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'FULL_TEXT',
      'weight' => '2',
      'function' => [
        'islandora_pdf_add_fulltext_derivative',
      ],
      'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
    ];
  }
  if (\Drupal::config('islandora_pdf.settings')->get('islandora_pdf_create_pdfa')) {
    $derivatives[] = [
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'PDFA',
      'weight' => '2',
      'function' => [
        'islandora_pdf_add_pdfa_derivative',
      ],
      'file' => drupal_get_path('module', 'islandora_pdf') . '/includes/derivatives.inc',
    ];
  }
  return $derivatives;
}
